[manifest]
version = "1.0.0"
dump_lua = true
priority = 99

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
-- TARGET: effects when cards are removed
'''
position = "after"
payload = '''
for i = 1, #scoring_hand do
    if SMODS.has_enhancement(scoring_hand[i], 'm_imaginary_werewolfCard') and not scoring_hand[i].debuff and scoring_hand[i].config.cardsToDestroy and #scoring_hand[i].config.cardsToDestroy > 0 then
        for j=1, #scoring_hand[i].config.cardsToDestroy do
            if SMODS.shatters(scoring_hand[i].config.cardsToDestroy[j]) then
                scoring_hand[i].config.cardsToDestroy[j].shattered = true
            else 
                scoring_hand[i].config.cardsToDestroy[j].destroyed = true
            end 
            cards_destroyed[#cards_destroyed+1] = scoring_hand[i].config.cardsToDestroy[j]
        end
    end
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "blind.lua"
pattern = '''
G.E_MANAGER:add_event(Event({func = function() G.play.cards[i]:juice_up(); return true end })) 
'''
position = "at"
payload = '''
G.E_MANAGER:add_event(Event({func = function() if G.play.cards[i] then G.play.cards[i]:juice_up(); end return true end })) 
'''
match_indent = true